- name: Upgrade de todos os pacotes do SO
  yum:
    name: '*'
    state: latest
- name: instalação do git client
  yum:
    name: git
    state: latest       
- name: Configurar os hosts lab Ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}" 
      with_items:
        - 192.168.56.2 control-node
        - 192.168.56.3 app01
        - 192.168.56.4 db01